#+lispworks8.1
(OBJC::DEFINE-PRECOMPILED-INVOKE-FUNCTIONS ((:FUNCTION (OBJC:OBJC-OBJECT-POINTER OBJC:SEL) (:POINTER (OBJC::OBJC-NAMED-STRUCT "CGContext")))))
#+(and lispworks8 (not lispworks8.1))
(OBJC::DEFINE-PRECOMPILED-INVOKE-FUNCTIONS ((:FUNCTION (OBJC:OBJC-OBJECT-POINTER OBJC:SEL OBJC:OBJC-OBJECT-POINTER OBJC:OBJC-OBJECT-POINTER (:UNSIGNED :LONG-LONG) (:POINTER :VOID)) :VOID)))
